packages:
  - 'packages/components/*'
  - 'packages/platform/*'
  - 'packages/apps/*'

shared-workspace-lockfile: true

allowBuilds:
  '@swc/core': true
  'esbuild': true
  'rs-module-lexer': true

minimumReleaseAge: 0
