// This file is auto-generated by the string extraction script.
// Do not edit this file manually.

export interface LocalizedStringEntry {
  component: string;
  string: string;
  context: string;
}

export const localizedStrings: LocalizedStringEntry[] = [
  {
    "component": "uibit-360-viewer",
    "string": "360 degree product view. Use drag, arrow keys, or buttons to rotate.",
    "context": "aria-label on viewer"
  },
  {
    "component": "uibit-360-viewer",
    "string": "Rotate left",
    "context": "aria-label on prev button"
  },
  {
    "component": "uibit-360-viewer",
    "string": "Rotate right",
    "context": "aria-label on next button"
  },
  {
    "component": "uibit-carousel",
    "string": "Content Carousel",
    "context": "aria-label on root region"
  },
  {
    "component": "uibit-carousel",
    "string": "Go to slide {n}",
    "context": "aria-label on indicator button (interpolated)"
  },
  {
    "component": "uibit-carousel",
    "string": "Next slide",
    "context": "aria-label on next button"
  },
  {
    "component": "uibit-carousel",
    "string": "Previous slide",
    "context": "aria-label on prev button"
  },
  {
    "component": "uibit-carousel",
    "string": "Slide {n} of {total}",
    "context": "aria-label on each slide (interpolated)"
  },
  {
    "component": "uibit-carousel",
    "string": "Slides",
    "context": "aria-label on indicator tablist"
  },
  {
    "component": "uibit-countdown",
    "string": "Countdown timer",
    "context": "aria-label on timer container"
  },
  {
    "component": "uibit-countdown",
    "string": "Days",
    "context": "Unit label"
  },
  {
    "component": "uibit-countdown",
    "string": "Hours",
    "context": "Unit label"
  },
  {
    "component": "uibit-countdown",
    "string": "Minutes",
    "context": "Unit label"
  },
  {
    "component": "uibit-countdown",
    "string": "Seconds",
    "context": "Unit label"
  },
  {
    "component": "uibit-hotspot",
    "string": "Close details",
    "context": "aria-label on close button"
  },
  {
    "component": "uibit-hotspot",
    "string": "Hotspot",
    "context": "Fallback aria-label on trigger button"
  },
  {
    "component": "uibit-hotspot",
    "string": "Hotspot details",
    "context": "Fallback aria-label on popover"
  },
  {
    "component": "uibit-scratch-reveal",
    "string": "Scratch to reveal",
    "context": "Instructions overlay text"
  },
  {
    "component": "uibit-scratch-reveal",
    "string": "Scratch-off panel to reveal content",
    "context": "aria-label on canvas container"
  },
  {
    "component": "uibit-scroll-progress",
    "string": "Scroll progress indicator",
    "context": "aria-label on progress bar"
  },
  {
    "component": "uibit-sentiment-selector",
    "string": "Sentiment rating",
    "context": "aria-label on radiogroup"
  },
  {
    "component": "uibit-table",
    "string": "{n} row(s) selected",
    "context": "Selection banner count (interpolated)"
  },
  {
    "component": "uibit-table",
    "string": "Clear all filters",
    "context": "aria-label on clear button"
  },
  {
    "component": "uibit-table",
    "string": "Clear filters",
    "context": "Active filters button label"
  },
  {
    "component": "uibit-table",
    "string": "Clear selection",
    "context": "Selection banner button"
  },
  {
    "component": "uibit-table",
    "string": "Column filters",
    "context": "aria-label on filter row"
  },
  {
    "component": "uibit-table",
    "string": "Columns",
    "context": "Column chooser button"
  },
  {
    "component": "uibit-table",
    "string": "Comfortable",
    "context": "UI text content"
  },
  {
    "component": "uibit-table",
    "string": "Compact",
    "context": "UI text content"
  },
  {
    "component": "uibit-table",
    "string": "Data table",
    "context": "aria-label on table region"
  },
  {
    "component": "uibit-table",
    "string": "Density:",
    "context": "Toolbar label"
  },
  {
    "component": "uibit-table",
    "string": "Export as CSV",
    "context": "aria-label on export button"
  },
  {
    "component": "uibit-table",
    "string": "Export CSV",
    "context": "Export button label (no selection)"
  },
  {
    "component": "uibit-table",
    "string": "Filter {column}",
    "context": "aria-label on column filter input (interpolated)"
  },
  {
    "component": "uibit-table",
    "string": "Next",
    "context": "aria-label on next page button"
  },
  {
    "component": "uibit-table",
    "string": "Normal",
    "context": "UI text content"
  },
  {
    "component": "uibit-table",
    "string": "Pagination",
    "context": "aria-label on pagination nav"
  },
  {
    "component": "uibit-table",
    "string": "Previous",
    "context": "aria-label on previous page button"
  },
  {
    "component": "uibit-table",
    "string": "Row density",
    "context": "aria-label on density select"
  },
  {
    "component": "uibit-table",
    "string": "Rows per page",
    "context": "aria-label on rows-per-page select"
  },
  {
    "component": "uibit-table",
    "string": "Rows:",
    "context": "Toolbar label"
  },
  {
    "component": "uibit-table",
    "string": "Search table",
    "context": "aria-label on search input"
  },
  {
    "component": "uibit-table",
    "string": "Select all {n} rows",
    "context": "Selection banner button (interpolated)"
  },
  {
    "component": "uibit-table",
    "string": "Select all rows on this page",
    "context": "aria-label on select-all checkbox"
  },
  {
    "component": "uibit-table",
    "string": "Select row",
    "context": "aria-label on row checkbox"
  }
];
